#!/bin/bash
#
# restart
#
# Simple bash script to remove the temporary pid and sockets for 
# notify server and restart the server.

SOCKET=/tmp/test.sock
PID=/tmp/test.pid
CONFIG=~/.notify.conf

# Remove old socket and pid.
rm $SOCKET
rm $PID

# Restart server.
./notify --config $CONFIG --socket $SOCKET --pidfile $PID
