#!/bin/bash
#
# restart
#
# Simple bash script to start the server and clean up.

# Get args.
key="$1"
case $key in
-d|--debug)
  MODE="debug"
  ;;
*)
  MODE="default"
  ;;
esac

SOCKET=/tmp/test.sock
PID=/tmp/test.pid
CONFIG=~/.notify.conf

# Remove old socket and pid.
rm $SOCKET
rm $PID

# Restart server.
case $MODE in
"default")
  ./notify --config=$CONFIG --socket=$SOCKET --pidfile=$PID
  ;;
"debug")
  perl -MDebug -d notify --config=$CONFIG --socket=$SOCKET --pidfile=$PID
  ;;
*)
  # unknown
  # option
  ;;
esac
