#! /bin/sh
# postinst script for notify

set -e

case "$1" in
    configure)
      if ! getent passwd notify 2>&1 >/dev/null; then
         # the account doesn't exist... time to create it
         echo "Adding notify system user ..."
         adduser --quiet --system --group --home /dev/null notify
         adduser --quiet notify adm
      fi

      if [ ! -d /var/lib/notify ]; then
          mkdir /var/lib/notify
          chown notify:root /var/lib/notify
      fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#
#DEBHELPER#
#

exit 0
