#! /bin/sh
# postrm script for notify

set -e

case "$1" in
       purge)
         rm -rf /var/lib/notify ||true
         if getent passwd notify 2>&1 >/dev/null; then
             echo -n "Removing notify system user.."
             userdel notify
             echo ".done"
         fi

         ;;
       remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
         ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac

#DEBHELPER#

exit 0
